### ISSUE TITLE
Update the copyright

### ISSUE THREAD

**Issue by rocboronat** [costular/leuksna-moon-app#33]
The copyright includes this lovely line: `Copyright [yyyy] [name of copyright owner]` 😂

**Comment by costular** [comment]
Hi @rocboronat!

First of all, sorry for being late with this reply.
Thanks for pointing it out, sometimes these things happen... 😛 

I've fixed it!

**Comment by rocboronat** [comment]
Haha, yes, of course, don't worry 😊
